baseurl: ""
url: https://www.areteos.io/
title: Areteos Coin
email: mustofa@binary.com
author: Amam
description: "Areteos Coin is a stablecoin thatâ€™s backed by the Global Group, giving you preferential access to a world of investment opportunities."

# Build settings
markdown: kramdown
permalink: pretty

sass:
  sass_dir: styles
  style: compressed

plugins:
  - jekyll-compress-images
  
compress_images:
  images_path: "./**/*.{gif,png,jpg,jpeg,svg}"

exclude: ['styles/abstracts', 'styles/base', 'styles/components','styles/layouts','styles/pages','_compress_images_cache.yml']

imageoptim:
  pngout: true
  svgo: true
  verbose: false